---
- name: build and deploy
  hosts: apps
  become: true
  tasks: 
     - name:
       copy:
        src: '{{ item }}'
        dest: /var/lib/tomcat/webapps
       with_fileglob: "target/hello-*.war"